---
name: "Charts: Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '!charts/**/README.md'

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - { name: "Checkout build repo", uses: "actions/checkout@v4", with: { fetch-depth: 0 } } # helm releaser needs the whole history
      - { name: "Setup Helm", uses: "azure/setup-helm@v4.0.0", with: { version: "3.14.1" } } # v4 only does not work?

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Funny enough, this does not support publishing to OCI, but we have k8s-avengers/helm-oci's tooci for that.
      - name: Run chart-releaser # this requires "gh-pages" branch to be present & GH pages configured
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
